name: DevSecOps Pipeline

on:
  push:

permissions:
  contents: read
  security-events: write  # разрешает загружать SARIF в Code Scanning

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: pip install -r requirements.txt

      - run: echo "Tests OK"

      - uses: github/codeql-action/init@v2
        with:
          languages: python

      - uses: github/codeql-action/analyze@v2